version: '3'

services:
    db:
        image: 'mysql:latest'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '27017:27017'
    api:
        build: .
        restart: always
        command: sh -c "npm install && npm run dev"
        volumes:
            - .:/src
        ports:
            - "3000:3000"
        environment:
            PORT: 3000
        depends_on:
            - db
